"""The CNI, for the providers the CLI has to install itself.

No pod schedules without a CNI, and ArgoCD is a pod — so the CNI must exist
before the thing that manages everything else does. That chicken-and-egg is
permanent, and it is why this module lives in the CLI rather than in
infra/services/.

It only bites for a CNI that is a separate install. `flannel` is bundled inside
the k3s binary and started by k3s before the API server is serving, so there is
nothing here to do and `install()` returns immediately — the chicken-and-egg
does not arise at all. That is the current provider; see
docs/decisions/0011-flannel-over-calico.md. The Calico path below is kept
because reversing that decision should be a config change, not a rewrite.
"""

from __future__ import annotations

import time

from ..config import Cluster
from ..errors import HomelabError
from ..runner import Runner

TIGERA_OPERATOR_URL = (
    "https://raw.githubusercontent.com/projectcalico/calico/{version}/manifests/tigera-operator.yaml"
)


def installation_manifest(cluster: Cluster) -> str:
    """The Calico Installation CR, with the pod CIDR taken from cluster.yaml so it
    cannot drift from what k3s was actually told to use."""
    return f"""\
# Generated by `homelab install` from clusters/{cluster.name}/cluster.yaml.
# Not committed: the pod CIDR must match k3s's --cluster-cidr exactly, and the
# only way to guarantee that is to derive both from the same source.
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    ipPools:
      - blockSize: 26
        cidr: {cluster.spec.k3s.clusterCIDR}
        encapsulation: {cluster.spec.cni.encapsulation}
        natOutgoing: Enabled
        nodeSelector: all()
---
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {{}}
"""


def operator_url(cluster: Cluster) -> str:
    return TIGERA_OPERATOR_URL.format(version=cluster.spec.cni.version)


def is_installed(runner: Runner) -> bool:
    return runner.run(
        ["kubectl", "get", "installation", "default"], check=False, mutates=False
    ).ok


def install(runner: Runner, cluster: Cluster, *, attempts: int = 30, delay: int = 5) -> None:
    # flannel needs no install step: k3s brings it up itself from
    # --flannel-backend, before this code could run anyway.
    if cluster.spec.cni.provider in ("none", "flannel"):
        return

    runner.run(
        ["kubectl", "apply", "--server-side", "-f", operator_url(cluster)], timeout=300
    )

    # The Installation CRD is registered by the operator asynchronously, so the
    # first apply usually loses the race. Retrying is simpler and more robust
    # than trying to wait on a CRD that may not exist yet to be waited on.
    manifest = installation_manifest(cluster)
    for attempt in range(1, attempts + 1):
        result = runner.run(
            ["bash", "-c", f"kubectl apply -f - <<'EOF'\n{manifest}\nEOF"], check=False
        )
        if result.ok:
            return
        if attempt == attempts:
            raise HomelabError(
                f"Calico Installation CR still rejected after {attempts} attempts "
                f"({attempts * delay}s). Last error:\n{result.stderr.strip()}"
            )
        time.sleep(delay)


def wait_for_nodes_ready(runner: Runner, timeout: int = 300) -> None:
    runner.run(
        ["kubectl", "wait", "--for=condition=Ready", "node", "--all", f"--timeout={timeout}s"],
        timeout=timeout + 60,
    )
