"""Initialise and unseal OpenBao without a human in the loop.

OpenBao starts sealed and uninitialised, and its volume is on local-path
(ADR 0008), so `homelab nuke` destroys it and every rebuild needed the whole
ceremony again: run `bao operator init`, copy three keys out of the terminal,
store them somewhere, then paste two of them back in. That put a manual step in
the path of a cluster that is meant to be rebuilt on a whim.

This automates it. The keys are generated here, encrypted with age, and written
to clusters/<name>/openbao-unseal.enc.yaml — which is NOT applied to the
cluster, only read back by this module to unseal after a rebuild.

WHAT THAT COSTS, stated plainly: OpenBao's unseal keys now live in the same
repository, protected by the same age key, as the SOPS bootstrap secrets. Its
protection at rest is therefore equal to SOPS's, not better than it. Anyone
holding the age key holds OpenBao.

What OpenBao still buys, and why this is a defensible trade rather than a
pointless one, is the runtime half: dynamic short-lived credentials, rotation
without a redeploy, per-application policies, and an audit log. None of that is
weakened by where the unseal keys sleep.

The upgrade that restores the separation is auto-unseal against an external KMS,
at which point these keys stop existing at all. See
docs/decisions/0013-automated-openbao-init.md.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import yaml

from ..errors import HomelabError
from ..runner import Runner

NAMESPACE = "openbao"
POD = "openbao-0"
DEFAULT_SHARES = 3
DEFAULT_THRESHOLD = 2


def unseal_path(repo_root: Path, cluster_name: str) -> Path:
    return repo_root / "clusters" / cluster_name / "openbao-unseal.enc.yaml"


def _bao(runner: Runner, *args: str, check: bool = True) -> str:
    result = runner.run(
        ["kubectl", "-n", NAMESPACE, "exec", POD, "--", "bao", *args],
        check=check, timeout=120, mutates=False,
    )
    return result.stdout


def status(runner: Runner) -> dict:
    """`bao status` exits non-zero when sealed, which is not an error here."""
    out = _bao(runner, "status", "-format=json", check=False)
    try:
        return json.loads(out)
    except (ValueError, TypeError):
        raise HomelabError(
            "could not read `bao status` — is the openbao pod running?"
        ) from None


def pod_ready(runner: Runner) -> bool:
    """Running, not necessarily Ready: a sealed OpenBao is 0/1 by design, so
    waiting for Ready before unsealing would wait forever."""
    result = runner.run(
        ["kubectl", "-n", NAMESPACE, "get", "pod", POD,
         "-o", "jsonpath={.status.phase}"],
        check=False, timeout=60, mutates=False,
    )
    return result.ok and result.stdout.strip() == "Running"


def initialize(runner: Runner, shares: int, threshold: int) -> dict:
    """Returns {"unsealKeys": [...], "rootToken": "..."}.

    The caller must never log this. It is the only copy that will ever exist.
    """
    out = _bao(
        runner, "operator", "init",
        f"-key-shares={shares}", f"-key-threshold={threshold}", "-format=json",
    )
    try:
        raw = json.loads(out)
    except (ValueError, TypeError):
        raise HomelabError("`bao operator init` did not return JSON") from None

    keys = raw.get("unseal_keys_b64") or raw.get("unseal_keys_hex") or []
    token = raw.get("root_token", "")
    if len(keys) < threshold or not token:
        raise HomelabError(
            f"init returned {len(keys)} keys and "
            f"{'a' if token else 'no'} root token — refusing to continue with "
            "a payload that cannot unseal the store."
        )
    return {"unsealKeys": keys, "rootToken": token}


def save(path: Path, payload: dict) -> None:
    """Encrypt with sops and write.

    Deliberately bypasses Runner: it has no stdin, so the alternatives were
    putting the keys in argv (logged, and visible in `ps`) or writing plaintext
    to a temp file first. Both are how a secret escapes. sops reads the
    plaintext on stdin and only the ciphertext ever reaches the filesystem.
    """
    doc = {
        "_comment": (
            "Generated by `homelab bootstrap`. NOT applied to the cluster — read "
            "back only to unseal after a rebuild. See ADR 0013."
        ),
        **payload,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        result = subprocess.run(
            ["sops", "--encrypt", "--filename-override", str(path), "/dev/stdin"],
            input=yaml.safe_dump(doc, sort_keys=False),
            capture_output=True, text=True, timeout=120, check=False,
        )
    except FileNotFoundError:
        raise HomelabError("sops is not installed; cannot store the unseal keys") from None
    if result.returncode != 0:
        # stderr only — stdout would be the ciphertext, stdin was the plaintext.
        raise HomelabError(f"sops refused to encrypt the unseal keys: {result.stderr.strip()[:200]}")
    path.write_text(result.stdout)
    path.chmod(0o600)


def load(runner: Runner, path: Path) -> dict:
    if not path.is_file():
        raise HomelabError(
            f"{path} does not exist, and OpenBao is already initialised.\n"
            "Its unseal keys are not recoverable — the store must be "
            "re-initialised, which means deleting its PVC."
        )
    plaintext = runner.run(["sops", "--decrypt", str(path)], mutates=False, timeout=120).stdout
    doc = yaml.safe_load(plaintext) or {}
    keys = doc.get("unsealKeys") or []
    if not keys:
        raise HomelabError(f"{path} contains no unsealKeys")
    return {"unsealKeys": keys, "rootToken": doc.get("rootToken", "")}


def unseal(runner: Runner, keys: list[str], threshold: int) -> None:
    """Submit keys until it opens. Each is passed as an argument to a command
    running inside the pod, so it is visible in that container's process list
    for the moment it runs — acceptable because the pod is the thing being
    unsealed, and unavoidable without a stdin-capable exec path."""
    for key in keys[:threshold]:
        _bao(runner, "operator", "unseal", key, check=False)
    if status(runner).get("sealed", True):
        raise HomelabError(
            f"still sealed after submitting {threshold} keys — they may not "
            "match this store (was it re-initialised without updating the file?)"
        )


def ensure(
    runner: Runner,
    repo_root: Path,
    cluster_name: str,
    *,
    shares: int = DEFAULT_SHARES,
    threshold: int = DEFAULT_THRESHOLD,
) -> str:
    """Idempotent. Returns a one-line outcome for the caller to print."""
    path = unseal_path(repo_root, cluster_name)
    st = status(runner)

    if not st.get("initialized", False):
        payload = initialize(runner, shares, threshold)
        save(path, payload)
        unseal(runner, payload["unsealKeys"], threshold)
        return f"initialised ({shares} shares, threshold {threshold}) and unsealed; keys -> {path.name}"

    if st.get("sealed", True):
        payload = load(runner, path)
        unseal(runner, payload["unsealKeys"], threshold)
        return "already initialised — unsealed from the stored keys"

    return "already initialised and unsealed"
